### PR TITLE
Adding a couple more unit tests.

### PR DESCRIPTION
**Pull request by NickMale**

### CODE REVIEW

**Comment by NickMale** [comment]
@alexwaibel if there's multiple extensions it takes the last one, it's just finding the last period and taking the substring after that. Duplicate filenames causes an overwrite.

**Comment by NickMale** [comment]
I'm going to be honest I don't have much time this weekend to address this.

**Comment by NickMale** [comment]
May just want to flag any changes as an issue.

**Comment by alexwaibel** [comment]
> @alexwaibel if there's multiple extensions it takes the last one, it's just finding the last period and taking the substring after that. Duplicate filenames causes an overwrite.

Overwriting files is probably not the behavior we want. It'd be really easy to accidentally overwrite an experiment for example and lose it forever. We can wait until next week to address it if you're busy but I think it would be good to throw an error instead of overwriting.

**Pull request merged**
